/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AuditCreateNestedManyWithoutMessagesInput } from "./AuditCreateNestedManyWithoutMessagesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { DeliveryCreateNestedManyWithoutMessagesInput } from "./DeliveryCreateNestedManyWithoutMessagesInput";
import { EnumMessageStatus } from "./EnumMessageStatus";
import { TemplateWhereUniqueInput } from "../../template/base/TemplateWhereUniqueInput";

@InputType()
class MessageCreateInput {
  @ApiProperty({
    required: false,
    type: () => AuditCreateNestedManyWithoutMessagesInput,
  })
  @ValidateNested()
  @Type(() => AuditCreateNestedManyWithoutMessagesInput)
  @IsOptional()
  @Field(() => AuditCreateNestedManyWithoutMessagesInput, {
    nullable: true,
  })
  audits?: AuditCreateNestedManyWithoutMessagesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  body?: string | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryCreateNestedManyWithoutMessagesInput,
  })
  @ValidateNested()
  @Type(() => DeliveryCreateNestedManyWithoutMessagesInput)
  @IsOptional()
  @Field(() => DeliveryCreateNestedManyWithoutMessagesInput, {
    nullable: true,
  })
  deliveries?: DeliveryCreateNestedManyWithoutMessagesInput;

  @ApiProperty({
    required: false,
    enum: EnumMessageStatus,
  })
  @IsEnum(EnumMessageStatus)
  @IsOptional()
  @Field(() => EnumMessageStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subject?: string | null;

  @ApiProperty({
    required: false,
    type: () => TemplateWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TemplateWhereUniqueInput)
  @IsOptional()
  @Field(() => TemplateWhereUniqueInput, {
    nullable: true,
  })
  template?: TemplateWhereUniqueInput | null;
}

export { MessageCreateInput as MessageCreateInput };
