/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AuditUpdateManyWithoutMessagesInput } from "./AuditUpdateManyWithoutMessagesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { DeliveryUpdateManyWithoutMessagesInput } from "./DeliveryUpdateManyWithoutMessagesInput";
import { EnumMessageStatus } from "./EnumMessageStatus";
import { TemplateWhereUniqueInput } from "../../template/base/TemplateWhereUniqueInput";

@InputType()
class MessageUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AuditUpdateManyWithoutMessagesInput,
  })
  @ValidateNested()
  @Type(() => AuditUpdateManyWithoutMessagesInput)
  @IsOptional()
  @Field(() => AuditUpdateManyWithoutMessagesInput, {
    nullable: true,
  })
  audits?: AuditUpdateManyWithoutMessagesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  body?: string | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryUpdateManyWithoutMessagesInput,
  })
  @ValidateNested()
  @Type(() => DeliveryUpdateManyWithoutMessagesInput)
  @IsOptional()
  @Field(() => DeliveryUpdateManyWithoutMessagesInput, {
    nullable: true,
  })
  deliveries?: DeliveryUpdateManyWithoutMessagesInput;

  @ApiProperty({
    required: false,
    enum: EnumMessageStatus,
  })
  @IsEnum(EnumMessageStatus)
  @IsOptional()
  @Field(() => EnumMessageStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subject?: string | null;

  @ApiProperty({
    required: false,
    type: () => TemplateWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TemplateWhereUniqueInput)
  @IsOptional()
  @Field(() => TemplateWhereUniqueInput, {
    nullable: true,
  })
  template?: TemplateWhereUniqueInput | null;
}

export { MessageUpdateInput as MessageUpdateInput };
